In [1]:
import pandas as pd
df = pd.read_csv("/home/aweiland/comparing_theories/mol_stats.csv")
df["egret_runtime"] = None
df.head()

,Unnamed: 0.1,Unnamed: 0,mol_id,num_atoms,xtb_rmsd,aimnet_rmsd,xtb_runtime,egret_runtime
0,0,0,20180169,40,0.241438,0.121931,15.357,None
1,1,1,20167551,41,0.150599,0.151843,18.821,None
2,2,2,2553,62,0.191888,0.078882,9.856,None
3,3,3,20175756,44,0.503976,0.215597,29.029,None
4,4,4,20168423,28,0.322589,0.059709,15.680,None

In [8]:
from ase.io import Trajectory


file = "/home/aweiland/comparing_theories/egret/egret_final/output/batch_1/mol_10021805/opt.traj"

traj = Trajectory(file)
atoms = traj[-1]


positions = atoms.get_positions()  # shape: (n_atoms, 3)
final_positions = []

for row in positions:
    fixed_row = [float(coord) for coord in row]  # optional: already floats
    final_positions.append(fixed_row)

    
symbols = atoms.get_chemical_symbols()

<class 'list'>

In [19]:
import os

for i in range(15):

    batch_path = f"/home/aweiland/comparing_theories/egret/egret_final/output/batch_{i}"

    all_xyz_path = "/home/aweiland/comparing_theories/egret/egret_final/egret_xyz"

    for directory in os.listdir(batch_path):
            subdir = os.path.join(batch_path, directory)
            file = os.path.join(subdir, "opt.traj")
            try:
                traj = Trajectory(file)
            except:
                print(directory)
                continue
            atoms = traj[-1]


            positions = atoms.get_positions()  # shape: (n_atoms, 3)
            final_positions = []

            for row in positions:
                fixed_row = [float(coord) for coord in row]  # optional: already floats
                final_positions.append(fixed_row)


            symbols = atoms.get_chemical_symbols()

            mol_id = directory.strip("mol_")

            output_file = os.path.join(all_xyz_path, "egret" + mol_id + ".xyz")
            f = open(output_file, "w")
            f.write(str(len(symbols))+ "\n\n")

            for i in range(len(symbols)):
                f.write(symbols[i] + "   " + str(final_positions[i][0]) 
                        + "   " + str(final_positions[i][1]) + "   " 
                        + str(final_positions[i][2]) + "\n")
            f.close()

mol_20207532
mol_20172787
mol_20122082
mol_22147
mol_20171682

In [5]:
#get time

import os
from datetime import datetime

for i in range(15):

    batch_path = f"/home/aweiland/comparing_theories/egret/egret_final/output/batch_{i}"

    all_xyz_path = "/home/aweiland/comparing_theories/egret/egret_final/egret_xyz"

    for directory in os.listdir(batch_path):
            subdir = os.path.join(batch_path, directory)
            file = os.path.join(subdir, "opt.log")
            
            mol_id = int(directory.strip("mol_"))
            
            with open(file, "r") as f:
                lines = f.readlines()
                try:
                    start = lines[1].split()[2]
                    end = lines[-1].split()[2]
                except IndexError:
                    pass



                fmt = "%H:%M:%S"
                t1 = datetime.strptime(start, fmt)
                t2 = datetime.strptime(end, fmt)

                #handles situation where job starts one day and ends another 
                #which could create a negative time
                if start[0] == "2" and end[0] == "0":
                    start = "1-" + start
                    end = "2-" + end
                    fmt = "%d-%H:%M:%S"
                    t1 = datetime.strptime(start, fmt)
                    t2 = datetime.strptime(end, fmt)


                delta = t2 - t1

                seconds = delta.total_seconds()

                df.loc[df["mol_id"] == mol_id, "egret_runtime"] = seconds

In [6]:
df.head()

,Unnamed: 0.1,Unnamed: 0,mol_id,num_atoms,xtb_rmsd,aimnet_rmsd,xtb_runtime,egret_runtime
0,0,0,20180169,40,0.241438,0.121931,15.357,237.0
1,1,1,20167551,41,0.150599,0.151843,18.821,321.0
2,2,2,2553,62,0.191888,0.078882,9.856,494.0
3,3,3,20175756,44,0.503976,0.215597,29.029,162.0
4,4,4,20168423,28,0.322589,0.059709,15.680,281.0

In [7]:
df.to_csv("/home/aweiland/comparing_theories/mol_stats.csv")