In [2]:
#converts csv will all mols to only ones in the 5k dataset
import pandas as pd

mol_stats = pd.read_csv("/home/aweiland/comparing_theories/mol_stats.csv")
fivek = pd.read_csv("/home/aweiland/comparing_theories/dft_geometries/5k_mol_ids.csv")

In [8]:
merged = pd.merge(fivek, mol_stats, on ="mol_id", how="inner")
merged.head()

,Unnamed: 0_x,Unnamed: 0.1_x,mol_id,atom_index,Shift,atom_type,Unnamed: 0_y,Unnamed: 0.2,Unnamed: 0.1_y,Unnamed: 0.1.1,num_atoms,xtb_rmsd,aimnet_rmsd,xtb_runtime,egret_runtime,egret_rmsd
0,0,0,2192,0,108.4,6,6327,6327,6327,6327,57,0.567481,0.476640,28.857,464.0,0.003635
1,23,24,2194,0,12.9,6,4792,4792,4792,4792,27,0.145308,0.075593,10.976,373.0,0.002764
2,30,31,2198,0,144.8,6,125,125,125,125,48,0.121894,0.174574,5.158,278.0,0.001712
3,57,58,2202,1,69.4,6,5338,5338,5338,5338,40,0.200460,0.129943,15.214,315.0,0.002875
4,69,70,2203,1,69.0,6,4112,4112,4112,4112,29,0.197792,0.104656,11.489,461.0,0.005081

In [19]:
merged.to_csv("/home/aweiland/comparing_theories/5k_mol_stats.csv", index=False)